// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQEleoJZlt5TDxE5jrvv4ZrtqaC7BJl4w',
    appId: '1:254359544181:web:1108daeb6012a3d949b33c',
    messagingSenderId: '254359544181',
    projectId: 'teraquiz-de13c',
    authDomain: 'teraquiz-de13c.firebaseapp.com',
    storageBucket: 'teraquiz-de13c.appspot.com',
    measurementId: 'G-K2L7MY0R5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBA745rqf92WqfGfvXjRK-xX-x-ubLSBw',
    appId: '1:254359544181:android:f4b062e0f937af1c49b33c',
    messagingSenderId: '254359544181',
    projectId: 'teraquiz-de13c',
    storageBucket: 'teraquiz-de13c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGOXbhZ5CVFCBtQbh7pjlNVq-ZvNHRktQ',
    appId: '1:254359544181:ios:38338e953f64b90849b33c',
    messagingSenderId: '254359544181',
    projectId: 'teraquiz-de13c',
    storageBucket: 'teraquiz-de13c.appspot.com',
    iosClientId: '254359544181-nmoc2ro900nm12v6emmhbb3bdpo671hu.apps.googleusercontent.com',
    iosBundleId: 'com.example.teraquiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGOXbhZ5CVFCBtQbh7pjlNVq-ZvNHRktQ',
    appId: '1:254359544181:ios:38338e953f64b90849b33c',
    messagingSenderId: '254359544181',
    projectId: 'teraquiz-de13c',
    storageBucket: 'teraquiz-de13c.appspot.com',
    iosClientId: '254359544181-nmoc2ro900nm12v6emmhbb3bdpo671hu.apps.googleusercontent.com',
    iosBundleId: 'com.example.teraquiz',
  );
}
